// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Database;

namespace OnlineShop.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230313014823_AddInitPhoto")]
    partial class AddInitPhoto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShop.Database.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.CompareProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CompareProducts");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.FavoriteProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99fb36b0-c926-41c7-8f78-b5bddf11a842"),
                            Name = "/images/image1.jpg",
                            ProductId = "8a5cf474-c473-48e1-bc3e-bbe0f22a80f2"
                        },
                        new
                        {
                            Id = new Guid("324152d7-65b5-4483-ab9a-c61eab4cd7a9"),
                            Name = "/images/image2.jpg",
                            ProductId = "e6d46e32-765c-487d-bf57-78759b32a47c"
                        },
                        new
                        {
                            Id = new Guid("153f4067-794e-4e33-906a-12eb4e61e51e"),
                            Name = "/images/image3.jpg",
                            ProductId = "59d7a46d-79a2-4a09-b6ad-a2333c3d3dcc"
                        },
                        new
                        {
                            Id = new Guid("836cc5ff-756a-4db2-8995-e79e814c9d01"),
                            Name = "/images/image4.jpg",
                            ProductId = "b41fefb9-1c66-4f2a-86af-090ada282060"
                        },
                        new
                        {
                            Id = new Guid("d942d587-9216-4ffb-97f3-54c30fa97a1f"),
                            Name = "/images/image5.jpg",
                            ProductId = "36211d90-17e0-42d0-9f3b-3b17d2885ec1"
                        },
                        new
                        {
                            Id = new Guid("699286c0-dfc6-44bd-b31b-d271362b652d"),
                            Name = "/images/image6.jpg",
                            ProductId = "968bfe01-31ba-44c0-a7c8-d1d04c1ffeb5"
                        });
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeliveryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryInfoId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.OrderDeliveryInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Agree")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderDeliveryInfo");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a5cf474-c473-48e1-bc3e-bbe0f22a80f2"),
                            Cost = 35000000m,
                            CreationDateTime = new DateTime(2023, 3, 13, 4, 48, 22, 178, DateTimeKind.Local).AddTicks(5815),
                            Description = "super",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = new Guid("e6d46e32-765c-487d-bf57-78759b32a47c"),
                            Cost = 25000000m,
                            CreationDateTime = new DateTime(2023, 3, 13, 4, 48, 22, 179, DateTimeKind.Local).AddTicks(8162),
                            Description = "best",
                            Name = "Lambo"
                        },
                        new
                        {
                            Id = new Guid("59d7a46d-79a2-4a09-b6ad-a2333c3d3dcc"),
                            Cost = 5000000m,
                            CreationDateTime = new DateTime(2023, 3, 13, 4, 48, 22, 179, DateTimeKind.Local).AddTicks(8208),
                            Description = "good",
                            Name = "Camaro"
                        },
                        new
                        {
                            Id = new Guid("b41fefb9-1c66-4f2a-86af-090ada282060"),
                            Cost = 7000000m,
                            CreationDateTime = new DateTime(2023, 3, 13, 4, 48, 22, 179, DateTimeKind.Local).AddTicks(8216),
                            Description = "good",
                            Name = "Mustang"
                        },
                        new
                        {
                            Id = new Guid("36211d90-17e0-42d0-9f3b-3b17d2885ec1"),
                            Cost = 7000m,
                            CreationDateTime = new DateTime(2023, 3, 13, 4, 48, 22, 179, DateTimeKind.Local).AddTicks(8220),
                            Description = "not bad",
                            Name = "Volga"
                        },
                        new
                        {
                            Id = new Guid("968bfe01-31ba-44c0-a7c8-d1d04c1ffeb5"),
                            Cost = 700m,
                            CreationDateTime = new DateTime(2023, 3, 13, 4, 48, 22, 179, DateTimeKind.Local).AddTicks(8229),
                            Description = "foo",
                            Name = "Kopeyka"
                        });
                });

            modelBuilder.Entity("OnlineShop.Database.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.Database.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Database.Models.Order", null)
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Database.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.CompareProduct", b =>
                {
                    b.HasOne("OnlineShop.Database.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.FavoriteProduct", b =>
                {
                    b.HasOne("OnlineShop.Database.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Image", b =>
                {
                    b.HasOne("OnlineShop.Database.Models.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId1");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.Database.Models.OrderDeliveryInfo", "DeliveryInfo")
                        .WithMany()
                        .HasForeignKey("DeliveryInfoId");

                    b.Navigation("DeliveryInfo");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Order", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Database.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
